### ISSUE TITLE
"eigen" and "no SNP left" errors

### ISSUE THREAD

**Issue by as239** [ramachandran-lab/PEGASUS#2]
Hi Priya,

This time I am running PEGASUS on a file I have generated myself. In some cases it produces these errors. These errors do not seem to be linked; the "no SNPs" error shows up more frequently.

Starting chromosome 2

ERROR: Stopping as there are no SNPs left for analysis

Error in eigen(m, only.values = TRUE, symmetric = TRUE) : 0 x 0 matrix
Calls: is.positive.definite -> eigen
Execution halted
 
I will be grateful for your advice on these matters.
Thank you and best wishes,
--Anastasia

**Comment by prnakka** [comment]
This most likely had to do with duplicate SNP ids in the input file, as discussed over email.
