### ISSUE TITLE
SNPs being used are just the rs-XXXX ones

### ISSUE THREAD

**Issue by antoniocollesei** [ramachandran-lab/PEGASUS#4]
Hi!

I am trying to launch pegasus to analyze data in plink format.
After running the GWAS test directly via plink, I am able to extract p-values at SNP level. Below a sample of what I am feeding pegasus:

...
_rs61793644_	0.2809
**chr4:11253**	0.03545
_rs150938622_	0.02089
_rs189831852_	0.3388
_rs113211263_	0.9627
**chr4:11637**	0.8714
_rs201817105_	0.359
...

My issue is connected to the fact that lots of SNP are defined not only with "rs-XXXX" but also "**chr1:12345**" (just an example). In the pegasus output all genes seem to point to an rs-like SNP, making me wonder whether the others have been recognized and used at all. Here some pegasus output:

Chr Gene nSNPs Start Stop Test-Stat Pvalue Error Best-SNP SNP-pvalue
4 AADAT 100 170981372 171011372 50.3857788042544 0.74735616389234 1.42030810751848e-14 _rs3806826_ 0.00407200000000002
4 AASDH 120 57204456 57253638 156.331866343933 0.241811547631046 2.31650964059827e-14 _rs7696217_ 0.02278
4 ABCE1 40 146019155 146050676 36.9256961478516 0.419128191877772 1.54909145320221e-14 _rs11947956_ 0.1548
4 ABCG2 103 89011415 89080011 74.6738990003276 0.664648896310203 8.37086198309038e-15 _rs11097183_ 0.01905
4 ABLIM2 325 7967036 8160559 256.212778725215 0.776982367484592 9.76422802143959e-15 _rs7696745_ 0.0168999999999999
4 ACCN5 94 156750880 156787425 39.204473836299 0.935414092955334 1.88025385636787e-14 _rs2125795_ 0.01122

Can you please give me a hint? Maybe I am misunderstanding, but if I wasn't could you suggest a workaround?
Thank you so much and keep up the good work!

**Comment by smithsap** [comment]
Thank you for reaching out about this issue. I believe that the default LD file from the 1000 genomes only has SNPs labeled by their rs numbers in the hg37 build. It may be that you will have to map the chr#-###### format to rs numbers (see https://www.biostars.org/p/72066/ for a discussion). Additionally, if you have access to genotype data you could calculate a custom ld file from your data using the -r flag in plinkv1.90. 

Let me know how else we can help!

**Comment by antoniocollesei** [comment]
@smithsap Awesome, thanks so much for your reply.
Since I have access to genotype data, I was able to calculate the ld file and use it as reference.

I think we can close this as resolved!
